_target_: deletme3D.models.segmentation_module.SegmentationLitModule

defaults:
  - _self_
  - net: multiscale_unet.yaml
  - criterion: dice_focal.yaml
  - optimizer: adamw.yaml
  - scheduler: one_cycle_lr.yaml

# compile model for faster training with pytorch 2.0
compile: false
scheduler_interval: epoch
