_target_: deletme3D.models.components.multiscale_unet.MultiScaleUNet
spatial_dims: 3
# Must be specified in code at runtime depending on the selected timesteps
in_channels: 3
# Always binary classification
out_channels: 1
# channels: [16, 32, 64, 128, 256, 512]
channels: [32, 64, 128, 256, 512, 1024]
strides: [2, 2, 2, 2, 2]
norm: "batch"
num_res_units: 3
bias: False
dropout: 0
downsample_factors: ${downsample_factors}
output_names:
  - model.1.submodule.2
  - model.1.submodule.1.submodule.2
